const predefinedSkills = [
  { skill: "JavaScript", logo: "/logos/javascript.png" },
  { skill: "React", logo: "/logos/react.png" },
  { skill: "Node.js", logo: "/logos/nodejs.png" },
  { skill: "Python", logo: "/logos/python.png" },
  { skill: "Java", logo: "/logos/java.png" },
  { skill: "HTML5", logo: "/logos/html5.png" },
  { skill: "CSS3", logo: "/logos/css3.png" },
  { skill: "Angular", logo: "/logos/angular.png" },
  { skill: "Vue.js", logo: "/logos/vuejs.png" },
  { skill: "TypeScript", logo: "/logos/typescript.png" },
  { skill: "PHP", logo: "/logos/php.png" },
  { skill: "Ruby", logo: "/logos/ruby.png" },
  { skill: "C#", logo: "/logos/csharp.png" },
  { skill: "C++", logo: "/logos/cpp.png" },
  { skill: "Go", logo: "/logos/golang.png" },
  { skill: "Kotlin", logo: "/logos/kotlin.png" },
  { skill: "Swift", logo: "/logos/swift.png" },
  { skill: "SQL", logo: "/logos/sql.png" },
  { skill: "MySQL", logo: "/logos/mysql.png" },
  { skill: "PostgreSQL", logo: "/logos/postgresql.png" },
  { skill: "MongoDB", logo: "/logos/mongodb.png" },
  { skill: "Firebase", logo: "/logos/firebase.png" },
  { skill: "Docker", logo: "/logos/docker.png" },
  { skill: "Kubernetes", logo: "/logos/kubernetes.png" },
  { skill: "AWS", logo: "/logos/aws.png" },
  { skill: "Azure", logo: "/logos/azure.png" },
  { skill: "Google Cloud", logo: "/logos/googlecloud.png" },
  { skill: "Git", logo: "/logos/git.png" },
  { skill: "GitHub", logo: "/logos/github.png" },
  { skill: "Bitbucket", logo: "/logos/bitbucket.png" },
  { skill: "GraphQL", logo: "/logos/graphql.png" },
  { skill: "Sass", logo: "/logos/sass.png" },
  { skill: "Webpack", logo: "/logos/webpack.png" },
  { skill: "Tailwind CSS", logo: "/logos/tailwindcss.png" },
  { skill: "Bootstrap", logo: "/logos/bootstrap.png" },
  { skill: "Jest", logo: "/logos/jest.png" },
  { skill: "Mocha", logo: "/logos/mocha.png" },
  { skill: "Cypress", logo: "/logos/cypress.png" },
  { skill: "Electron", logo: "/logos/electron.png" },
  { skill: "Next.js", logo: "/logos/nextjs.png" },
  { skill: "Nuxt.js", logo: "/logos/nuxtjs.png" },
];

export default predefinedSkills;
